version: "3"
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=prestashop-db # name of db
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3306:3306"
    networks:
      - prestashop # name of network - allow containers to communicate with
                   # each other
  prestashop:
    image: "prestashop/prestashop:1.7"
    restart: always
    container_name: app
    environment:
      DB_SERVER: db
    ports: 
      - "8080:80"
    networks:
      - prestashop
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    networks:
      - prestashop
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: admin

networks:
  prestashop: