<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQfrxHkP\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQfrxHkP/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerQfrxHkP.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerQfrxHkP\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerQfrxHkP\appAppKernelProdContainer([
    'container.build_hash' => 'QfrxHkP',
    'container.build_id' => '0c7eff54',
    'container.build_time' => 1669079082,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQfrxHkP');
