<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL0rv08l\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL0rv08l/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL0rv08l.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL0rv08l\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerL0rv08l\appAppKernelDevDebugContainer([
    'container.build_hash' => 'L0rv08l',
    'container.build_id' => '1bb69acc',
    'container.build_time' => 1674436604,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL0rv08l');
